import React from 'react'
import Head from 'next/head'

const Layout = ({children}: any) => {
    return (
        <>
            <Head>
                <title>Leanplum Task</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main>
                {children}
            </main>
        </>
    )
};

export default Layout;
